# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: | # runs during either prebuild (if enabled) or first startup
      git remote add mdn https://github.com/mdn/content.git
      yarn
    command: | # runs every startup
      yarn start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    onOpen: open-preview
